### ISSUE TITLE
TextMate 2 support

### ISSUE THREAD

**Issue by vmtelecom** [desoi/pgedit-textmate#1]
Hi, is this bundles working with TextMate 2? Because I can not get it work somehow :)
I can see that it's not update for almost a year, but would it be possible to update it for TextMate 2?

Thanks

**Comment by desoi** [comment]
Hi, it is my understanding that TextMate 2 is still in development with no announced release schedule. I'll be happy to look into it once there is a release commitment.

**Comment by vmtelecom** [comment]
Hi, TextMate 2 was released in August as open source (http://blog.macromates.com/2012/textmate-2-at-github/), so you can download and compile it from GitHub (https://github.com/textmate/textmate) or download a prebuilt binary.

**Comment by desoi** [comment]
I'm aware that it is available, but it is still in development and subject to change. If you are certain the bundle API is completely stable and documented, please point me to that commitment.

I'm happy to take patches and contributions if you want to tackle the fixes while TM2 is still in development.

**Comment by wellsoliver** [comment]
Seconding porting this to TM2. I think it's in wide use by now...

**Comment by desoi** [comment]
Allan Odgaard (TM lead developer) mentioned last week that TM2 is still "alpha" and needs more work before it can be considered a replacement for TM 1.x. See

http://lists.macromates.com/textmate/2013-February/035896.html

**Comment by desoi** [comment]
pgEdit is now compatible with TextMate 2. Download the latest master branch here or see the link below for more details.

http://pgedit.com/pgedit-textmate-2-2
